header_ids = {
    "r3VPAex5owCr": 'Team',
    '0bA3n3mGJF73': 'Season Type',
    'HsLPcUfLez6M': 'Primary Contact First Name',
    'ANq7STdkwbMn': 'Primary Contact Last Name',
    'JZVlRZK8v4iq': 'Primary Phone Number',
    'nXusRbbFaZ7U': 'Primary Email',
    '1AYhn4GBqDtr': 'Street Address',
    'Igibp9WNDxW6': 'Address Line 2',
    'cHmDwjaKE3Wc': 'City',
    'jo56ZhXPyWdP': 'State',
    'XiGLRRwzjZnv': 'Zip/Postal',
    'fpFv2NGmxczQ': 'Country',
    'KDi6D0egUmac': 'is Shipping Address?',
    'p7x3DPcpN3V7': 'Shipping Address',
    'xOQeP1CCiB9U': 'Shipping Address Line 2',
    'qdQyn5IrXOki': 'Shipping City',
    'ZqYVaARZiP7A': 'Shipping State',
    'X8rLQAG5nTwh': 'Shipping Zip',
    '87l34zLs0bCq': 'Shipping Country',
    '7SQY8USPP5sM': 'Vehicle Model Year',
    'hpb9sx9ypek9': 'Race Car Identifier (RCI)',
    'bzs6dUuj5pXh': 'Transponder Number',
    'qXXxPmUc02Zk': '2024 Registered Number',
    'beOE34tDj10M': 'Car # First Choice',
    'dvXOPSgcHYi0': 'Car # Second Choice',
    'YsiAJayV3rDd': 'Car # Third Choice',
    'Gb8xhO8J6l1y': 'Driver 1 First Name',
    'UWNtVkkBqIdc': 'Driver 1 Last Name',
    '7aB4V7MQwA6m': 'Driver 1 Nationality',
    '5dzTWCytVDqS': 'Driver 1 Hometown',
    'gMmqV0QGV3eK': 'Driver 1 Email',
    'hPSFyLZiIO4Q': 'Driver 1 Cell',
    'upQGt3gsRO9v': 'Driver 1 FIA Rating',
    'LV1Ubw4Vb5Vk': 'Crew Chief First Name',
    'pDgeHdSQ0gHK': 'Crew Chief Last Name',
    'TNuBuAlf0XGI': 'Crew Chief Email',
    'Speh4GSidbiv': 'Crew Chief Cell',
    'l7xuGchnCsbR': 'Team Manager First Name',
    '2LKDZIeiPBvV': 'Team Manager Last Name',
    'Mb6LQcbmnnqK': 'Team Manager Email',
    'iOqiM28gR1qq': 'Team Manager Cell',
    'VUKZ1whXZHHy': 'Has Marketing/PR Rep',
    'WTj56QkmzxGQ': 'PR First Name',
    'FonnamfMvrdV': 'PR Last Name',
    'Glc17XNyX4bL': 'PR Email',
    'FQqYOuM7tKpY': 'PR Cell Number',
    '7gZDyAP5RCmY': 'Truck Driver First Name',
    'KP5KLIewL0GE': 'Truck Driver Last Name',
    'BZHbrT6oVwle': 'Truck Driver Cell',
    'XdWIzzMQcN4M': 'Truck Driver Email',
    'XcQXrudlWne9': 'Additional Emails'
}

headers = [
    'Team',
    'Season Type',
    'Primary Contact First Name',
    'Primary Contact Last Name',
    'Primary Phone Number',
    'Primary Email',
    'Street Address',
    'Address Line 2',
    'City',
    'State',
    'Zip/Postal',
    'Country',
    'is Shipping Address?',
    'Shipping Address',
    'Shipping Address Line 2',
    'Shipping City',
    'Shipping State',
    'Shipping Zip',
    'Shipping Country',
    'Vehicle Model Year',
    'Race Car Identifier (RCI)',
    'Transponder Number',
    '2024 Registered Number',
    '2025 Confirmed Number',
    'Car # First Choice',
    'Car # Second Choice',
    'Car # Third Choice',
    'Driver 1 First Name',
    'Driver 1 Last Name',
    'Driver 1 Nationality',
    'Driver 1 Hometown',
    'Driver 1 Email',
    'Driver 1 Cell',
    'Driver 1 FIA Rating',
    'Crew Chief First Name',
    'Crew Chief Last Name',
    'Crew Chief Email',
    'Crew Chief Cell',
    'Team Manager First Name',
    'Team Manager Last Name',
    'Team Manager Email',
    'Team Manager Cell',
    'Has Marketing/PR Rep',
    'PR First Name',
    'PR Last Name',
    'PR Email',
    'PR Cell Number',
    'Truck Driver First Name',
    'Truck Driver Last Name',
    'Truck Driver Cell',
    'Truck Driver Email',
    'Additional Emails',
    'id',
    'Submitted_at'
]

gr_num_headers = [
    'Team',
    '2024 Confirmed Number',
    'Car # First Choice',
    'Car # Second Choice',
    'Car # Third Choice',
    'Driver 1 First Name',
    'Driver 1 Last Name',
    'has RSP',
    'Submitted_at'
]
