header_ids = {
    "gjEkJoPuuxl9": 'Team',
    'ibjVDS9AWxf4': 'Season Type',
    'rKWXzcxPOSgU': 'Entrant License Name',
    'FQQy6lGffhDj': 'Primary Contact First Name',
    '0u7hLux0YxpW': 'Primary Contact Last Name',
    '5MeGOHMCJdTw': 'Primary Phone Number',
    'QwSY6Zx7xa4R': 'Primary Email',
    'VewEavhf57OU': 'Street Address',
    'ovYx0eu0giMW': "Address line 2",
    '0NfZET3OUr7G': 'City',
    '84EU1JYZTwmV': 'State',
    '9g9uZVCSTosq': 'Zip/Postal',
    'FJW5XL6OM0bE': 'Country',
    'obYiuCRB2Zyf': 'is Shipping Address?',
    'Qu1EGnv1JZOw': 'Shipping Address',
    'IVHN3SlYCmAg': 'Shipping Address Line 2',
    'ere4gQZFynV1': 'Shipping City',
    'CvOk8EpvBEmT': 'Shipping State',
    'pjUlxjhxKBgF': 'Shipping Zip',
    'FDNtSPjLYlLD': 'Shipping Country',
    'rLextKxq7NOb': 'Vehicle Model Year',
    'bEaMbjJfGEfs': 'Vehicle Make & Model',
    '1O8QGBP3CuuV': 'Homologation Number',
    'BAGCqZ0a46fI': 'Transponder Number',
    '2ixpVfqzC5cZ': 'Series',
    'qpIxQJlGsU8a': 'Class',  # TC A
    'VUS8zmSTzlpi': 'Class',    # GT America class
    'bpJBRPAjHTHA': 'Class',  # GTWC
    'M1ydodEf082T': 'Class',  # GT4
    'ebw8my83CaZJ': '2025 Registered Number',
    'TYApDPz8Okk5': 'Car # First Choice',
    '8GBRbFnL5S3X': 'Car # Second Choice',
    'TNkhKs0vuCVV': 'Car # Third Choice',
    'FEfAKB55TEnQ': 'Driver 1 First Name',  
    'yM6mBP3Y4ggc': 'Driver 1 Last Name',
    'VccoVdyqhq8v': 'Driver 1 Nationality',
    'xXPs501ZTJiM': 'Driver 1 Email',
    'hbA9Mn2ZR8IB': 'Driver 1 Cell',
    'Icb6c6b04YvS': 'Driver 1 FIA Rating',
    'ka5hrCFUqUHO': 'Driver 2 First Name',
    '212uCGWuLtil': 'Driver 2 Last Name',
    'rPqF562HGT57': 'Driver 2 Nationality',
    "550Azf8MMlEc": 'Driver 2 Email',
    'AbgaqGKccKio': 'Driver 2 Cell',
    '48P8AAnAUm8F': 'Driver 2 FIA Rating',
    'WvXU8oK2i6at': 'Crew Chief First Name',
    'ebsM8EEXwIaX': 'Crew Chief Last Name',
    'rZdrG8t6Rk1l': 'Crew Chief Email',
    'LaLXIj8f6bGs': 'Crew Chief Cell',
    'IrICq6BgD4Ig': 'Team Manager First Name',
    'C61wlnwW9Rnv': 'Team Manager Last Name',
    'kEgvrs5MPJW0': 'Team Manager Email',
    'gABjx8JNrt1D': 'Team Manager Cell',
    'jqXoNVFcrQM8': 'Has Marketing/PR Rep',
    'HcB3AQtBFjly': 'PR First Name',
    '1SPlAH1eT1ny': 'PR Last Name',
    'QMR6j9oBpgBv': 'PR Email',
    'JBUcsTcjEy7H': 'PR Cell Number',
    'B3Pa5LyyuiXt': 'Truck Driver First Name',
    'XdXQa2hxcBPd': 'Truck Driver Last Name',
    '7gZJkzq1oyFR': 'Truck Driver Cell',
    'bI3w3S6FEk4s': 'Truck Driver Email',
    'FRKQss88gWuI': '2026 Share',
    'ITpGFcV6Koau': 'Additional Emails'
}

headers = [
    'Team',
    'Season Type',
    'Entrant License Name',
    'Primary Contact First Name',
    'Primary Contact Last Name',
    'Primary Phone Number',
    'Primary Email',
    'Street Address',
    'Address line 2',
    'City',
    'State',
    'Zip/Postal',
    'Country',
    'is Shipping Address?',
    'Shipping Address',
    'Shipping Address Line 2',
    'Shipping City',
    'Shipping State',
    'Shipping Zip',
    'Shipping Country',
    'Vehicle Model Year',
    'Vehicle Make & Model',
    'Homologation Number',
    'Transponder Number',
    'Series',
    'Class',
    '2025 Registered Number',
    '2026 Confirmed Number',
    'Car # First Choice',
    'Car # Second Choice',
    'Car # Third Choice',
    'Driver 1 First Name',
    'Driver 1 Last Name',
    'Driver 1 Nationality',
    'Driver 1 Email',
    'Driver 1 Cell',
    'Driver 1 FIA Rating',
    'Driver 2 First Name',
    'Driver 2 Last Name',
    'Driver 2 Nationality',
    'Driver 2 Email',
    'Driver 2 Cell',
    'Driver 2 FIA Rating',
    'Crew Chief First Name',
    'Crew Chief Last Name',
    'Crew Chief Email',
    'Crew Chief Cell',
    'Team Manager First Name',
    'Team Manager Last Name',
    'Team Manager Email',
    'Team Manager Cell',
    'Has Marketing/PR Rep',
    'PR First Name',
    'PR Last Name',
    'PR Email',
    'PR Cell Number',
    'Truck Driver First Name',
    'Truck Driver Last Name',
    'Truck Driver Cell',
    'Truck Driver Email',
    '2026 Share',
    'Additional Emails',
    'id',
    'Submitted_at'
]

sro_num_headers = [
    'Team',
    'Series',
    '2024 Confirmed Number',
    'Car # First Choice',
    'Car # Second Choice',
    'Car # Third Choice',
    'Driver 1 First Name',
    'Driver 1 Last Name',
    'has RSP',
    'Submitted_at'
]
