headers = {
    "CI2u1enwoqbZ": 'Team',
    '1rK745G7gN0S': 'Season Type',
    'FhYKXAVPkzaa': 'Entrant License Name',
    '6r2CqolmpepU': 'Primary Contact First Name',
    '4kIVm0yJCqFq': 'Primary Contact Last Name',
    '9OF0lWZEpNuR': 'Primary Phone Number',
    'xK89Tz19ICpG': 'Primary Email',
    'EfGE75l0Boh7': 'Street Address',
    '5MpSspTvu4g1': 'City',
    'nx7RCtskler7': 'State',
    'UAadJT7CwKOT': 'Zip/Postal',
    'PDYzPKydUlta': 'Country',
    'VWorxkTstwgd': 'is Shipping Address?',
    '5RrYGTeKRdXg': 'Vehicle Model Year',
    'IMEA0t0c9kyQ': 'Vehicle Make',
    'ASWurX5GTtnv': 'Vehicle Model',
    'Bw8p4QECsDvD': 'Series',
    'qpIxQJlGsU8a': 'Class',
    'zgosMYsLCGMP': '2023 Registered Number',
    'e1R9xecDplrr': 'Car # First Choice',
    'qx4hoS0Vg3qp': 'Car # Second Choice',
    'Or4qETiPiW1s': 'Car # Third Choice',
    'l3XaoUZhURCO': 'Driver 1 First Name',  # double check this id later
    'kkdqAVRNWpxC': 'Driver 1 Last Name',
    'y3Y4IBZhU0Iv': 'Driver 1 Nationality',
    'XAgm4jYd0AKO': 'Driver 1 Hometown',
    'uorVE07hxoDO': 'Driver 1 Country',
    'LAmMqTDTQ1l0': 'Driver 1 Email',
    'kAyKLuWx2BBQ': 'Driver 1 Cell',
    'lOTS3iQkQB8y': 'Crew Chief First Name',
    'JmxVkIHn8bcG': 'Crew Chief Last Name',
    'kPWqIohZqJpX': 'Crew Chief Email',
    'dPFyek6nmENk': 'Crew Chief Cell',
    'GefSkyJGJeaY': 'Team Manager First Name',
    'MKtN5Qz3XZtq': 'Team Manager Last Name',
    'liGvRZ25kY8F': 'Team Manager Email',
    'EwUHxcy8cbOq': 'Team Manager Cell',
    'jMLsSqMcowgJ': 'Has Marketing/PR Rep',
    '2ft6nbuGOp33': 'Truck Driver First Name',
    'wPqzta91f8N9': 'Truck Driver Last Name',
    'X9NvIhhJnLjM': 'Truck Driver Cell',
    'mP6QpRkzO92E': 'Truck Driver Email'
}
