header_ids = {
    "CI2u1enwoqbZ": 'Team',
    '1rK745G7gN0S': 'Season Type',
    'FhYKXAVPkzaa': 'Entrant License Name',
    '6r2CqolmpepU': 'Primary Contact First Name',
    '4kIVm0yJCqFq': 'Primary Contact Last Name',
    '9OF0lWZEpNuR': 'Primary Phone Number',
    'xK89Tz19ICpG': 'Primary Email',
    'EfGE75l0Boh7': 'Street Address',
    '5MpSspTvu4g1': 'City',
    'nx7RCtskler7': 'State',
    'UAadJT7CwKOT': 'Zip/Postal',
    'PDYzPKydUlta': 'Country',
    'VWorxkTstwgd': 'is Shipping Address?',
    'e1seFQ6XDBKR': 'Shipping Address',
    'zd6ni0urg088': 'Shipping City',
    'LentMWK47C5a': 'Shipping State',
    'AkUcLiG3vIv4': 'Shipping Zip',
    '007OZfYZNpgb': 'Shipping Country',
    '5RrYGTeKRdXg': 'Vehicle Model Year',
    'IMEA0t0c9kyQ': 'Vehicle Make',
    'ASWurX5GTtnv': 'Vehicle Model',
    'pU2Jkm90w9Eq': 'Homologation Number',
    'XNElqQKjsuNZ': 'Transponder Number',
    'Bw8p4QECsDvD': 'Series',
    'qpIxQJlGsU8a': 'Class',  # TC A
    '5IwbUAdTNi0d': 'Class',    # GT A
    'P78moOw8ctap': 'Class',  # GTWC
    'b3OYPsZLzund': 'Class',  # GT4
    'zgosMYsLCGMP': '2023 Registered Number',
    'e1R9xecDplrr': 'Car # First Choice',
    'qx4hoS0Vg3qp': 'Car # Second Choice',
    'Or4qETiPiW1s': 'Car # Third Choice',
    'l3XaoUZhURCO': 'Driver 1 First Name',  # double check this id later
    'kkdqAVRNWpxC': 'Driver 1 Last Name',
    'y3Y4IBZhU0Iv': 'Driver 1 Nationality',
    'XAgm4jYd0AKO': 'Driver 1 Hometown',
    'uorVE07hxoDO': 'Driver 1 Country',
    'LAmMqTDTQ1l0': 'Driver 1 Email',
    'kAyKLuWx2BBQ': 'Driver 1 Cell',
    'CkpqrMl1TEZz': 'Driver 1 FIA Rating',
    'NV0lUHjFkzMk': 'Driver 2 First Name',
    'CRH2iIZnu1uc': 'Driver 2 Last Name',
    'YrigzdcNTGil': 'Driver 2 Nationality',
    'dpsJee4rggd4': 'Driver 2 Hometown',
    'CdTxxS8rMTmX': 'Driver 2 Country',
    'Td5Ev7tmr3ar': 'Driver 2 Email',
    '0c5rUqtsHKOX': 'Driver 2 Cell',
    'khMPZOQu2qR6': 'Driver 2 FIA Rating',
    'lOTS3iQkQB8y': 'Crew Chief First Name',
    'JmxVkIHn8bcG': 'Crew Chief Last Name',
    'kPWqIohZqJpX': 'Crew Chief Email',
    'dPFyek6nmENk': 'Crew Chief Cell',
    'GefSkyJGJeaY': 'Team Manager First Name',
    'MKtN5Qz3XZtq': 'Team Manager Last Name',
    'liGvRZ25kY8F': 'Team Manager Email',
    'EwUHxcy8cbOq': 'Team Manager Cell',
    'jMLsSqMcowgJ': 'Has Marketing/PR Rep',
    'wz2OiJVuoXf4': 'PR First Name',
    'EGP3O3cCPhNf': 'PR Last Name',
    'KMa9phUiY1rH': 'PR Email',
    'aSRPTx3OGrB8': 'PR Cell Number',
    '2ft6nbuGOp33': 'Truck Driver First Name',
    'wPqzta91f8N9': 'Truck Driver Last Name',
    'X9NvIhhJnLjM': 'Truck Driver Cell',
    'mP6QpRkzO92E': 'Truck Driver Email',
    'yRllyFLLhJNF': 'Additional Emails'
}

headers = [
    'Team',
    'Season Type',
    'Entrant License Name',
    'Primary Contact First Name',
    'Primary Contact Last Name',
    'Primary Phone Number',
    'Primary Email',
    'Street Address',
    'City',
    'State',
    'Zip/Postal',
    'Country',
    'is Shipping Address?',
    'Shipping Address',
    'Shipping City',
    'Shipping State',
    'Shipping Zip',
    'Shipping Country',
    'Vehicle Model Year',
    'Vehicle Make',
    'Vehicle Model',
    'Homologation Number',
    'Transponder Number',
    'Series',
    'Class',
    '2023 Registered Number',
    '2024 Confirmed Number',
    'Car # First Choice',
    'Car # Second Choice',
    'Car # Third Choice',
    'Driver 1 First Name',
    'Driver 1 Last Name',
    'Driver 1 Nationality',
    'Driver 1 Hometown',
    'Driver 1 Country',
    'Driver 1 Email',
    'Driver 1 Cell',
    'Driver 1 FIA Rating',
    'Driver 2 First Name',
    'Driver 2 Last Name',
    'Driver 2 Nationality',
    'Driver 2 Hometown',
    'Driver 2 Country',
    'Driver 2 Email',
    'Driver 2 Cell',
    'Driver 2 FIA Rating',
    'Crew Chief First Name',
    'Crew Chief Last Name',
    'Crew Chief Email',
    'Crew Chief Cell',
    'Team Manager First Name',
    'Team Manager Last Name',
    'Team Manager Email',
    'Team Manager Cell',
    'Has Marketing/PR Rep',
    'PR First Name',
    'PR Last Name',
    'PR Email',
    'PR Cell Number',
    'Truck Driver First Name',
    'Truck Driver Last Name',
    'Truck Driver Cell',
    'Truck Driver Email',
    'Additional Emails',
    'id',
    'Submitted_at'
]

sro_num_headers = [
    'Team',
    'Series',
    '2024 Confirmed Number',
    'Car # First Choice',
    'Car # Second Choice',
    'Car # Third Choice',
    'Driver 1 First Name',
    'Driver 1 Last Name',
    'has RSP',
    'Submitted_at'
]
